Feat/registro
okitauehara/Projeto_11_Linkr pull request #1
Opened 2021-09-15 20:12 UTC by pedrohotz

2021-09-15 21:20 UTC, ninidora commented on src/Components/Registro.js
> +    const [url,setURL] = useState("");
E se isso fosse um objeto? 🤔

2021-09-15 21:26 UTC, ninidora requested changes

2021-09-15 21:26 UTC, ninidora commented on src/Components/Registro.js
> +       }
Seria uma boa adicionar um status code 500 com "Não foi possível realizar o cadastro no momento. Tente novamente mais tarde."

2021-09-15 21:26 UTC, ninidora commented on src/Components/Registro.js
> +           <span>Switch back to login</span>
Tem que setar aqui para ir para o Login.

2021-09-15 22:37 UTC, okitauehara submitted a review, later dismissed
Novamente, após as mudanças sugeridas, acredito que esteja ok

2021-09-16 14:18 UTC, ninidora approved these changes, later dismissed

2021-09-16 14:20 UTC, okitauehara approved these changes, later dismissed

2021-09-16 14:24 UTC, ninidora submitted a review, later dismissed

2021-09-16 14:25 UTC, okitauehara submitted a review, later dismissed

2021-09-16 14:59 UTC, ninidora approved these changes, later dismissed

2021-09-16 15:01 UTC, ninidora approved these changes

2021-09-16 15:01 UTC, okitauehara approved these changes, later dismissed

2021-09-16 15:03 UTC, ninidora approved these changes, later dismissed

2021-09-16 15:47 UTC, ninidora approved these changes

2021-09-16 15:47 UTC, okitauehara approved these changes

2021-09-16 15:47 UTC, merged