Feat/likes
okitauehara/Projeto_11_Linkr pull request #12
Opened 2021-09-18 19:12 UTC by Kadugs

2021-09-19 01:12 UTC, ninidora commented
O tooltip está com atraso e eu tenho que tirar o mouse de cima e voltar para ele atualizar

2021-09-19 01:12 UTC, ninidora requested changes
O tooltip está com atraso e eu tenho que tirar o mouse de cima e voltar para ele atualizar

2021-09-20 13:50 UTC, ninidora submitted a review, later dismissed

2021-09-20 17:32 UTC, okitauehara approved these changes

2021-09-20 17:56 UTC, ninidora approved these changes

2021-09-20 17:56 UTC, merged