Feat/preview
okitauehara/Projeto_11_Linkr pull request #19
Opened 2021-09-22 22:22 UTC by pedrohotz

2021-09-22 23:56 UTC, okitauehara approved these changes, later dismissed

2021-09-23 12:35 UTC, ninidora requested changes

2021-09-23 12:35 UTC, ninidora commented on src/components/shared/UserPost.js
> +        var p = /^(?:https?:\/\/)?(?:www\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))((\w|-){11})(?:\S+)?$/;
Colocar nomes mais semanticos

2021-09-23 12:35 UTC, ninidora commented on src/components/shared/UserPost.js
> +                <div className="link-content" onClick={()=>setOpenFrame(true)}>
Tenta organizar melhor esse trecho de codigo

2021-09-23 14:57 UTC, okitauehara approved these changes

2021-09-23 19:19 UTC, ninidora approved these changes

2021-09-23 19:19 UTC, merged