Feat/view user posts
okitauehara/Projeto_11_Linkr pull request #2
Opened 2021-09-15 20:13 UTC by Kadugs

Ver os posts de um usuário ao acessar o link /user/:id

2021-09-15 22:44 UTC, okitauehara commented on src/components/templates/ContainerUserPost.js
> +    height:276px;
Acho interessante não fixar uma altura. Fiz um teste com um texto longo e o layout acabou quebrando. Imagino que colocar altura como auto deva resolver!

2021-09-15 22:50 UTC, okitauehara requested changes

2021-09-15 22:50 UTC, okitauehara commented on src/components/templates/ContainerUserPost.js
> +    height:276px;
Acho interessante não fixar uma altura. Fiz um teste com um texto longo e o layout acabou quebrando. Imagino que colocar altura como auto deva resolver!

2021-09-15 22:50 UTC, okitauehara commented on src/components/UserPosts/UserPosts.js
> +    .user-header img {
Pelo que vi do layout, esse header não possui uma imagem acompanhando o nome do usuário, mas se houver essa liberdade pode ser uma sugestão interessante

2021-09-15 22:50 UTC, okitauehara commented on src/components/templates/ContainerUserPost.js
> +
Procure elaborar o modelo para mobile para evitar passar em branco futuramente, além de já identificar possíveis problemas com o layout!

2021-09-15 23:13 UTC, Kadugs commented on src/components/templates/ContainerUserPost.js
> +    height:276px;
Boa! Substituí `height` por `min-height`, agora tá corrigido

2021-09-16 00:10 UTC, okitauehara approved these changes, later dismissed

2021-09-16 14:33 UTC, ninidora commented on src/App.js
>  import { BrowserRouter, Route, Switch } from 'react-router-dom';
Vai dar erro aqui por já ter passado.

2021-09-16 14:35 UTC, ninidora requested changes

2021-09-16 14:35 UTC, ninidora commented on src/App.js
> +        </Route>
Tirar esse Route aqui, **o b.o foi no conflito**.

2021-09-16 14:35 UTC, ninidora commented on src/components/templates/UserPost.js
> +// import { AiFillHeart } from 'react-icons/ai'
Limpar os comentários depois.

2021-09-16 14:51 UTC, ninidora approved these changes

2021-09-16 14:52 UTC, okitauehara approved these changes

2021-09-16 14:53 UTC, merged