Feat/Repost
okitauehara/Projeto_11_Linkr pull request #20
Opened 2021-09-23 00:04 UTC by Kadugs

Implementada funcionalidade de re-postar

2021-09-23 12:42 UTC, ninidora approved these changes, later dismissed

2021-09-23 12:42 UTC, ninidora commented on src/components/shared/ContainerUserPost.js
> +    /* margin-top: 20px; */
Retirar comentários que sejam trechos de código antigo.

2021-09-23 12:59 UTC, okitauehara requested changes

2021-09-23 12:59 UTC, okitauehara commented on src/components/shared/UserPost.js
> +                        <img src={linkImage} alt='' />
Acho que nesse trecho aqui a imagem do preview do link acaba se repetindo

2021-09-23 13:18 UTC, okitauehara submitted a review, later dismissed

2021-09-23 19:20 UTC, ninidora submitted a review, later dismissed

2021-09-23 20:34 UTC, okitauehara approved these changes

2021-09-24 17:26 UTC, ninidora approved these changes

2021-09-24 17:26 UTC, merged