First Commit Login
okitauehara/Projeto_11_Linkr pull request #3
Opened 2021-09-15 20:47 UTC by pedrohotz

2021-09-15 21:29 UTC, ninidora requested changes

2021-09-15 21:29 UTC, ninidora commented on src/Components/Login.js
> +import { useContext } from "react";
Trocar as linhas

```
import { useState } from "react";
import { useContext } from "react";
```

Por uma só:
`import { useState, useContext } from "react";`

2021-09-15 21:29 UTC, ninidora commented on src/Components/Login.js
> +        }
Seria uma boa adicionar um 500 aqui para "Não foi possível realizar o login nesse momento"

2021-09-15 21:29 UTC, ninidora commented on src/Components/Login.js
> +        </Link>
O link está errado aqui. A rota no registro é /registro, mas a certa é essa aqui.

2021-09-15 22:33 UTC, okitauehara commented on src/Components/Login.js
> +        const promisse = axios.post("https://mock-api.bootcamp.respondeai.com.br/api/v2/linkr/sign-in",body);
Mais pra frente, acho bacana juntar as requisições num API.js, coloquei alguns que utilizei na parte de criação de post. Deixo aqui apenas um lembrete!

2021-09-15 22:35 UTC, okitauehara submitted a review, later dismissed
Após as mudanças sugeridas pela Nivea acredito que a feat esteja ok para ir para main

2021-09-16 14:21 UTC, okitauehara approved these changes

2021-09-16 14:21 UTC, ninidora approved these changes

2021-09-16 14:21 UTC, merged